name: CI/CD DevSecOps

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest

      - name: Scan with Trivy (no exit on fail)
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov locally (no SARIF)
        run: |
          checkov -d . || true  # Pour éviter que le job échoue en cas de findings

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
