name: CI/CD DevSecOps

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest

      - name: Run Trivy (scan image)
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
          format: sarif
          output: trivy-results.sarif
          exit-code: 0
          severity: HIGH,CRITICAL

      - name: Upload Trivy report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov (scan IaC)
        run: checkov -d . --output-file-path checkov-results.sarif --output sarif || true

      - name: Upload Checkov report to GitHub Security tab
        if: ${{ hashFiles('checkov-results.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: checkov-results.sarif
