name: CI/CD DevSecOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-app .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@v0.16.1
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app
          format: table
          severity: CRITICAL,HIGH
        continue-on-error: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.2758.0
        with:
          directory: .
          framework: dockerfile,compose
        continue-on-error: true
